Feature/mt 41 enable sub and account
EQTPartners/netsuite-matching-tool pull request #13
Opened 2021-04-13 07:48 UTC by eliassendaniel

User-Event som skapar upp pre-check job för alla kombinationer subsidiary och account som är påslagna när antingen ett subsidiary eller account slås på.

sub-ue
> Givet att konto 1 och 2 är aktiverade
> När subsidiary 1 aktiveras
> Då kommer det att skapas pre-check job för
> { sub:1, kto: 1},{ sub:1, kto: 2}

konto-ue
> Givet att sub 12 och 25 är aktiverade
> När konto 5 aktiveras
> Då kommer det att skapas pre-check job för
> { sub:12, kto: 5},{ sub:25, kto: 5}

Har även kört linting på netsuite projektet.

2021-04-13 07:49 UTC, eliassendaniel commented
@emelieaspholm1 Lägger upp en draft PR. Tänker att det kan vara bra att kolla av denna story flera gånger då det nog blir mycket att reviewa totalt sett.

2021-04-13 08:35 UTC, emelieaspholm1 requested changes

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/helpers/recordHelper.ts
> +        return newRecord.save()
newRecord.save() returnerar en string, kommer detta fungera? Kommer det vara en string som skickas runt med TypeScript tror att det är ett number?

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/helpers/recordHelper.ts
> +        let temporaryValue = value
```suggestion
        let finalValue = value
```

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/helpers/recordHelper.ts
> +                    temporaryValue = formatDate(value as Date | string, purposes.RECORD)
```suggestion
                    finalValue = formatDate(value as Date | string, purposes.RECORD)
```

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/helpers/recordHelper.ts
> +                    value: temporaryValue
```suggestion
                    value: finalValue
```

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/hooks/account-toggled.ts
> +                ` }).asMappedResults() as { account: number, subsidiary: number }[]
Annan abstraktionsnivå, bryt ut till funktion. Borde nog till och med ligga i account service. Vi borde också fundera på om vi verkligen ska ha hårdkodade fält-id:n och record-id:n mitt i alla queries, känns egentligen inte så bra

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/hooks/subsidiary-toggle.ts
> +                WHERE subsidiary = ${subsidiaryId}
Samma som ovan, bryt ut till funktion och borde flyttas till subsidiary service. Går det att göra WITH alltså?? 😄

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/models/precheck-job/index.ts
> +        const conversion: unknown = query.runSuiteQL({ query: sql }).asMappedResults()
snyggt! såhär borde alla queries skrivas! Här är inget hårdkodat 👏

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/models/precheck-job/index.ts
> +}
blir lättare att läsa om dessa flyttas till egen fil, detta är inget jag behöver veta för att veta vad som går att göra på precheck-job

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/scripts/eqtmt-user-event-account-hook.ts
> +    const { CREATE, DELETE, EDIT } = scriptContext.UserEventType
vad händer på vid DELETE? Då finns inget newRecord och checkarna i "toggleAccount" lär inte fungera?

2021-04-13 08:35 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/scripts/eqtmt-user-event-subsidiary-hook.ts
> +    const { CREATE, DELETE, EDIT } = scriptContext.UserEventType
vad händer på vid DELETE? Då finns inget newRecord och checkarna i "toggleSubsidiary" lär inte fungera?

2021-04-13 09:43 UTC, eliassendaniel commented on netsuite/src/TypeScript/helpers/recordHelper.ts
> +        return newRecord.save()
Det står i dokumentationen att returtypen är number. 😖  Ska testa det.
![image](https://user-images.githubusercontent.com/50018060/114532740-6e303500-9c4d-11eb-95bd-1bb020713913.png)

2021-04-13 09:44 UTC, eliassendaniel commented on netsuite/src/TypeScript/helpers/recordHelper.ts
> +        return newRecord.save()
Körde det igår, men minns inte om det var innan eller efter refactor.

2021-04-13 09:46 UTC, eliassendaniel commented on netsuite/src/TypeScript/models/precheck-job/index.ts
> +        const conversion: unknown = query.runSuiteQL({ query: sql }).asMappedResults()
😎

2021-04-13 09:47 UTC, eliassendaniel commented on netsuite/src/TypeScript/hooks/subsidiary-toggle.ts
> +                WHERE subsidiary = ${subsidiaryId}
Ja. Så när jag försökte sist måste jag infört något syntaxfel eftersom jag trodde att det inte gick.

2021-04-13 09:47 UTC, eliassendaniel commented on netsuite/src/TypeScript/models/precheck-job/index.ts
> +}
Ja, det är på g.

2021-04-13 09:48 UTC, eliassendaniel commented on netsuite/src/TypeScript/scripts/eqtmt-user-event-account-hook.ts
> +    const { CREATE, DELETE, EDIT } = scriptContext.UserEventType
Gick av bara farten, ska nog inte vara där nu när du säger det. Tar bort det.

2021-04-13 09:48 UTC, eliassendaniel commented on netsuite/src/TypeScript/scripts/eqtmt-user-event-account-hook.ts
> +    const { CREATE, DELETE, EDIT } = scriptContext.UserEventType
```suggestion
    const { CREATE, EDIT } = scriptContext.UserEventType
```

2021-04-13 09:48 UTC, eliassendaniel commented on netsuite/src/TypeScript/scripts/eqtmt-user-event-account-hook.ts
> +    const { CREATE, DELETE, EDIT } = scriptContext.UserEventType
```suggestion
    const { CREATE, EDIT } = scriptContext.UserEventType
```

2021-04-13 09:48 UTC, eliassendaniel commented on netsuite/src/TypeScript/scripts/eqtmt-user-event-subsidiary-hook.ts
> +    const { CREATE, DELETE, EDIT } = scriptContext.UserEventType
```suggestion
    const { CREATE, EDIT } = scriptContext.UserEventType
```

2021-04-13 09:52 UTC, eliassendaniel commented on netsuite/src/TypeScript/hooks/account-toggled.ts
> +                ` }).asMappedResults() as { account: number, subsidiary: number }[]
Ja, det är ganska WIP just nu, så mycket att implementera. men borde snyggas till med konstanter och flyttas till modellen.

2021-04-13 09:52 UTC, eliassendaniel commented on netsuite/src/TypeScript/hooks/subsidiary-toggle.ts
> +                WHERE subsidiary = ${subsidiaryId}
samma som ovan, flyttas till modellen och refactor.

2021-04-13 13:40 UTC, eliassendaniel commented on netsuite/src/TypeScript/helpers/recordHelper.ts
> +        return newRecord.save()
Test igen, är inga problem.

2021-04-13 14:56 UTC, eliassendaniel commented
Nu är MR skelettet på plats och all logistik för att från att man togglat sub eller account på så kommer ett jobb skapas och börja processas.

2021-04-13 14:59 UTC, eliassendaniel commented on netsuite/src/TypeScript/hooks/account-toggled.ts
> +                ` }).asMappedResults() as { account: number, subsidiary: number }[]
fixat.

2021-04-13 14:59 UTC, eliassendaniel commented on netsuite/src/TypeScript/hooks/subsidiary-toggle.ts
> +                WHERE subsidiary = ${subsidiaryId}
ordnat!

2021-04-14 09:02 UTC, emelieaspholm1 approved these changes

2021-04-14 09:02 UTC, emelieaspholm1 commented on netsuite/src/TypeScript/scripts/eqtmt-mapreduce-process-precheck.ts
> +        if (jobs.length > 0) {
fix this

2021-04-15 08:43 UTC, eliassendaniel commented on netsuite/src/TypeScript/create-unmatched/pre-check-job-processor.ts
> +    // TODO: figure out if should yield a unmatch-job
coming up later 👯

2021-04-15 08:43 UTC, merged